import{a as u,S as m,A as v}from"./assets/vendor-DjtasW9M.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerPolicy&&(r.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?r.credentials="include":n.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(n){if(n.ep)return;n.ep=!0;const r=s(n);fetch(n.href,r)}})();const L="https://events-store.b.goit.study/api",c={CATEGORIES:"/categories",EVENTS:"/events",LIMIT:8};u.defaults.baseURL=L;async function E(){return(await u.get(c.CATEGORIES)).data}async function g(e=1,t=""){return t==="all"||!t?(await u.get(`${c.EVENTS}?page=${e}&limit=${c.LIMIT}`)).data:(await u.get(`${c.EVENTS}?page=${e}&limit=${c.LIMIT}&category=${t}`)).data}const o={categoriesListEl:document.querySelector(".js-event-category-list"),categoriesListOpenSvgBtn:document.querySelector(".icon-rotate"),caregoryListSelect:document.querySelector(".event-category-select"),categoriesListOpen:document.querySelector(".event-category-list"),eventsList:document.querySelector(".events-list"),firstCategoryButton:document.querySelector(".categories__btn"),showMoreBtn:document.querySelector(".show-more-btn"),loader:document.querySelector(".loader")};function w(e,t){const s=e%4,i=e-s;return s===0||t<i?"row-of-4":s===3?"row-last-3":s===2?"row-last-2":s===1?"row-last-1":""}function S(e){const t=[{_id:"all",name:"Всі події",tags:[]},...e],s=t.map(({_id:i,name:n,tags:r},a)=>`<li class="event-category-item ${w(t.length,a)}" data-category="${i}">
          <p class="event-category-title">${n}</p>
          <p class="event-category-tags">${r.map(y=>`#${y}, `).join(" ")}</p>
        </li>`).join("");o.categoriesListEl.innerHTML=s,o.firstCategoryButton&&o.firstCategoryButton.classList.add("categories__btn--active"),window.innerWidth<768&&!o.categoriesListEl.SimpleBar&&new m(o.categoriesListEl,{autoHide:!1})}o.caregoryListSelect.addEventListener("click",h);function h(e){o.categoriesListOpenSvgBtn.classList.toggle("icon-rotate-rotated"),o.categoriesListOpen.classList.toggle("is-hidden")}function f(e){const t=e.map(({_id:s,name:i,price:n,category:r,image:a})=>`<li class="event-item">
        <img
          src="${a}"
          alt="${i}"
          width="335"
          height="251"
        />
        <div class="event-info">
          <p class="event-title">${i}</p>
          <p class="event-text">${r.name}</p>
          <p class="event-price">від ${n.value} грн</p>
        </div>
        <button type="button" class="event-details-btn" data-event-id="${s}">Детальніше</button>
      </li>`).join("");o.eventsList.insertAdjacentHTML("beforeend",t)}let l=1,d="all";async function C(){try{const e=await E();S(e);const{events:t,totalItems:s}=await g(l,d);f(t),p(s)}catch(e){console.log("error events list",e)}}async function $(e){const t=e.target.closest(".event-category-item");if(!t)return;d=t.dataset.category,l=1,o.eventsList.innerHTML="";const{events:i,totalItems:n}=await g(l,d);f(i),p(n)}async function I(e){l+=1;const{events:t,totalItems:s}=await g(l,d);f(t),p(s)}function p(e){o.showMoreBtn.disabled=l*c.LIMIT>=e}document.addEventListener("DOMContentLoaded",C);o.categoriesListEl.addEventListener("click",$);o.showMoreBtn.addEventListener("click",I);new v(".accordion-container",{showMultiple:!1});
//# sourceMappingURL=index.js.map
